[package]
name = "light-organ-blah"
version = "0.1.0"
authors = ["phil <uniphil@gmail.com>"]

[dependencies]
goertzel = { git = "https://github.com/uniphil/goertzel", branch = "f32-samples" }
jack = "0.5.6"
lossyq = "0.1.19"
rust-hsluv = "0.1.3"
sdl2 = "0.31.0"
